name: tt-sketch
channels:
  - conda-forge
dependencies:
  - cython
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - mypy
  - numpy>=1.21
  - pandas
  - pip
  - pylint
  - pytest
  - pytables
  - scipy
  - sphinx
  - tqdm
  - pip:
    - black
    - nbsphinx
    - nbsphinx-link
    - pycodestyle
    - pytest-cov
    - sphinx_rtd_theme
